[package]
name = "web_version"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo-events = "0.1.2"
gloo-utils = "0.1.4"
wasm-bindgen = "0.2.81"
yew = "0.19.0"
common = { path = "../common" }